### ISSUE TITLE
How do I set my prefered stock list "

### ISSUE THREAD

**Issue by codepython** [Lightstreamer/Lightstreamer-example-StockList-adapter-java#4]

**Comment by Bravo27** [comment]
This Data Adapter simulate a market data feed which provides a list of 30 stock symbols (item1, item2, ... , item30) with updates prices and other fields.
At the client side the application can request any subset of this list through the itemized list provided with the subscribe request (for example ["item4", "item5", "item9", "item15"]).
You can also use a symbolic name instead of the detailed list, for example "MY_PREFER", but you'll need to extend the code of this Adapter to implement the getItems method of the MetadataAdapter interface in order to resolve an Item Group name into the list of stock symbols.

**Comment by codepython** [comment]
ok , thanks !

**Comment by codepython** [comment]
if I change the item1 to other name,it does not work fine.
what's the reason?

**Comment by Bravo27** [comment]
Please consider that if you change the name of an item, for example from 'item1' to 'my_stock_no1', you should take care to let the client and the Data Adapter consistent.
In the specific case of this Data Adapter you have to change the code of ExternalFeedSimulator in order to generate a feeds producer for the 'my_stock_no1' Item ([ExternalFeedSimulator.java#L120](https://github.com/Lightstreamer/Lightstreamer-example-StockList-adapter-java/blob/master/src/src_feed/stocklist_demo/feed_simulator/ExternalFeedSimulator.java#L120)).

**Comment by codepython** [comment]
problem is fixed, thanks

**Comment by codepython** [comment]
BTW,it it possible to support k-line and other chart line graph   in ios client?

**Comment by Bravo27** [comment]
The iOS client library does not provide any graphic widgets, but you can feed with the real-time updates received any third-party component suitable to your needs.

**Comment by codepython** [comment]
ok.
If I pull the real time updates from provided server , do I need to save the new data at local file to be used for data analysis?

**Comment by Bravo27** [comment]
Yes, with a MERGE type subscription should be your client to store the received data for any aggregate analysis.

But, leveraging other type of subscription mode (like DISTINCT or COMMAND) and the snapshot feature you could receive, against a subscription request, a historical series of data.
The feasibility and/or suitability of such a mechanism depends on the type and size of the historical data.
